/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as BoardsNewRouteImport } from './routes/boards.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsNewRoute = BoardsNewRouteImport.update({
  id: '/boards/new',
  path: '/boards/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/new': typeof BoardsNewRoute
  '/boards/': typeof BoardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/new': typeof BoardsNewRoute
  '/boards': typeof BoardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/new': typeof BoardsNewRoute
  '/boards/': typeof BoardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/goals'
    | '/journal'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/goals'
    | '/journal'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/goals'
    | '/journal'
    | '/login'
    | '/signup'
    | '/boards/$boardId'
    | '/boards/new'
    | '/boards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  BoardsNewRoute: typeof BoardsNewRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/boards'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/new': {
      id: '/boards/new'
      path: '/boards/new'
      fullPath: '/boards/new'
      preLoaderRoute: typeof BoardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BoardsNewRoute: BoardsNewRoute,
  BoardsIndexRoute: BoardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
